"""Ballout -> ballot

Revision ID: 0f99e1444d4f
Revises: 39d7ff0ed27d
Create Date: 2021-07-09 20:09:26.403971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f99e1444d4f'
down_revision = '39d7ff0ed27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('ballotGuid', sa.Integer(), nullable=False))
    op.drop_column('votes', 'balloutGuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('balloutGuid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('votes', 'ballotGuid')
    # ### end Alembic commands ###
