"""ballotGuid to string

Revision ID: 85f02cfd4cd9
Revises: 0f99e1444d4f
Create Date: 2021-07-11 00:41:29.807472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f02cfd4cd9'
down_revision = '0f99e1444d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'ballotGuid',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votes', 'ballotGuid',
               existing_type=sa.String(length=256),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
