"""Added electionId to votes

Revision ID: a09e6395e946
Revises: 85f02cfd4cd9
Create Date: 2021-07-11 11:28:48.189949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09e6395e946'
down_revision = '85f02cfd4cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('electionId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'elections', ['electionId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'electionId')
    # ### end Alembic commands ###
