"""ElectionDatabase initial migration

Revision ID: a63284931f7f
Revises: 
Create Date: 2021-07-08 17:56:06.461425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63284931f7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electionparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idParticipant', sa.Integer(), nullable=False),
    sa.Column('idElection', sa.Integer(), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idElection'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['idParticipant'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('balloutGuid', sa.Integer(), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('officialJMBG', sa.String(length=13), nullable=False),
    sa.ForeignKeyConstraint(['pollNumber'], ['electionparticipant.pollNumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('electionparticipant')
    op.drop_table('participants')
    op.drop_table('elections')
    # ### end Alembic commands ###
