"""Added votes

Revision ID: e55388a1dafc
Revises: a63284931f7f
Create Date: 2021-07-09 17:07:04.731611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e55388a1dafc'
down_revision = 'a63284931f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('balloutGuid', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('officialJMBG', sa.String(length=13), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pollNumber'], ['electionparticipant.pollNumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
